manavsiddharthgupta/promptIn.ai

app/signup/page.tsx

Added signup Page
- created signup page
- confirmation logic is yet to be implemented
- feedback is yet to be implemented

feature: added signup page

---

app/signin/page.tsx
app/signup/page.tsx

Updated Signup code 
check code format

update: signUp code updt and code format check

---

app/components/Button.tsx
app/components/InputField.tsx
app/signin/page.tsx

Added Css Tailwind in 
- SignIn
- Button
- InputField

ui: added css in signIn component

---

.prettierrc.json
app/components/Button.tsx
app/components/FormFeedback.tsx
app/components/InputField.tsx
app/signin/page.tsx
app/utils/hooks/useInputField.ts

Feedback logic 
- Toouched State
- Input Validation

feature: added form feedback logic

---

app/signup/page.tsx

- Added feedback logic
- updated ui
- updated signup page

feature: added feedback logic in form page and updated signup

---

app/signup/page.tsx

formatted the code: change tab space 4 to 2

bug: fixes the tab space indentation

---

app/components/Search.tsx
app/page.tsx
package-lock.json
package.json

added 
- search Bar
- prompts feed section
- nav

feature: updated home page ui

---

app/components/PromptCard.tsx

- added hashtag section in prompt card

feature: added hashtag section in prompt card

---

app/create-prompt/page.tsx
app/ui/PromptTextArea.tsx
app/ui/TitleInputField.tsx

FEAT: Added page to create a prompt
- *button to navigate back to home page*
- *Title Area*
- *Content Area*

feature: added page for creating a prompt

---

app/@feed/page.tsx
app/components/PromptCard.tsx
app/layout.tsx
app/page.tsx
app/ui/Card.tsx
app/ui/PromptCardIcons.tsx
package-lock.json
package.json

- used parallel roud for feed section
- updated icon in prompts card component

updated home page 

---

app/@modal/(.)prompts/[id]/page.tsx
app/components/prompt card/PromptBody.tsx
app/components/prompt card/PromptCard.tsx
app/components/prompt card/PromptCardOutline.tsx
app/components/prompt card/PromptHastags.tsx
app/components/prompt card/PromptHeader.tsx
app/prompts/[id]/page.tsx

added prompt card to 
- prompt modal
- prompt page

ui: added Prompt card ui to prompt modal and page

---

app/@modal/(.)prompts/[id]/page.tsx
app/components/prompt card/PromptCard.tsx
app/components/prompt card/PromptHeader.tsx
app/prompts/[id]/page.tsx

- rmv unnecessary props from Prompt Header

fix: profile and tags css

---

app/components/NavBar.tsx
app/create-prompt/page.tsx
app/signup/page.tsx
app/ui/Button.tsx

- updt sigup ui
- change button color

updated: signup page ui and change btn color

---

app/signup/page.tsx

fix: form validity

---

.env
app/api/auth/[...nextauth]/route.ts
middleware.ts

- upd env file
- added middleware

feature: securing pages using middleware

---

app/components/NavBar.tsx
app/components/profile bar/ProfileBar.tsx
app/utils/hooks/useClosePanel.ts

- added custom hooks useclosepanel
- updated navbar

added feature profile bar

---

app/components/Feed.tsx
app/components/Search.tsx
app/components/SearchExpanded.tsx
app/components/SearchPrompt.tsx
app/components/SearchUsers.tsx
app/components/profile/BookmarkedPrompts.tsx
app/components/profile/MyPrompts.tsx
app/components/profile/StarredPrompts.tsx
app/utils/store/sampledata.ts

- expanded should not dismiss when clicked on search section
- updated expand searchbar ui
- updated profile page with adding prompt, starred and bookmark feed

fix: search bar functionality

---

app/components/profile/Cropper.tsx
app/components/profile/ImageEdit.tsx
app/components/profile/ProfileEdit.tsx
app/utils/cropper/cropImage.ts
package-lock.json
package.json

- react-easy-cropper
- uploadthing

feature: avatar crop functionality

---

app/api/prompts/route.ts
prisma/migrations/20230705124614_init/migration.sql
prisma/schema.prisma

- added tags and connected to prompt model
- updtaed user model
- updated post method for prompt endpoint

updt: prisma schema and prompts endpoint

---

app/api/user/[avatarName]/route.ts

feature: profile endpoint

---

app/components/profile/ProfileCard.tsx
app/profile/[id]/page.tsx
app/ui/Icons.tsx

- [fix: svg inside div not found in server html](https://github.com/manavsiddharthgupta/promptIn.ai/pull/47/commits/09d54845f1d280f8b031a7fac45380ad65645df3)
- [feature: profile data will not cache](https://github.com/manavsiddharthgupta/promptIn.ai/pull/47/commits/c6d1f6f84f78e6233cd1259262e6fbce14d69f41)
- [fix: avatar img ui](https://github.com/manavsiddharthgupta/promptIn.ai/pull/47/commits/25e03d4147784cf5d532b71207eab4c86c85974e)

fix: profile ui, svg inside div and caching

---

app/@feed/page.tsx
app/@modal/(.)prompts/[id]/page.tsx
app/api/prompts/[id]/route.ts
app/api/prompts/route.ts
app/components/Feed.tsx
app/components/profile/ProfileFeed.tsx
app/components/prompt card/InteractiveIconActions.tsx
app/components/prompt card/PromptCard.tsx
app/components/prompt card/PromptHastags.tsx
app/components/prompt card/PromptHeader.tsx
app/lib/prompts.ts
app/lib/types/prompts.ts
app/prompts/[id]/page.tsx
app/ui/PromptCardIcons.tsx

- prompts/id endpoint
- fetch prompt data
- fix: hydration issue

feature: prompts/id endpoint and fetching prompt data

---

app/@modal/(.)prompts/[id]/page.tsx
app/components/prompt card/PromptBody.tsx
app/components/prompt card/PromptCard.tsx
app/components/prompt card/PromptHastags.tsx
app/components/prompt card/PromptHeader.tsx
app/create-prompt/page.tsx
app/lib/prompts.ts
app/ui/PromptTextArea.tsx
app/ui/TitleInputField.tsx
app/utils/hooks/useInputField.ts

- create prompt method
- update on feed
- fix: tag missing key props

update: post prompt method

---

app/api/user/[id]/route.ts
app/components/Feed.tsx
app/components/profile/BookmarkedPrompts.tsx
app/components/profile/MyPrompts.tsx
app/components/profile/ProfileComponent.tsx
app/components/profile/ProfileFeed.tsx
app/components/profile/StarredPrompts.tsx
app/lib/db.ts
app/lib/types/profile.ts
app/prompts/[id]/page.tsx

- [created, starred and bookmarked prompts in profile page](https://github.com/manavsiddharthgupta/promptIn.ai/commit/d1dde0761090575048b4067878fe49267fc7f08d)
- [fix: connecting to prisma](https://github.com/manavsiddharthgupta/promptIn.ai/commit/f1484190a1ef19f1b8d4afcf2e91311c0ccbec83)

feature: created, starred and bookmarked prompts in profile page

---

app/components/profile/BookmarkedPrompts.tsx
app/components/profile/ProfileFeed.tsx
app/components/profile/StarredPrompts.tsx
app/components/prompt card/InteractiveIconActions.tsx
app/lib/types/profile.ts

- fixed: getStarData when modal is dismissed
- fixed: starredData and bookmarkedData

fix: starred data, bookmarked data and getStarData

---

app/components/profile/ProfileComponent.tsx
app/components/profile/ProfileFeed.tsx
app/lib/types/prompts.ts
app/profile/[id]/layout.tsx
app/profile/[id]/page.tsx

fix: feed component fetching logic

---

app/api/prompts/[id]/bookmark/route.ts
app/components/prompt card/InteractiveIconActions.tsx

- created bookmark endpoint
- bookmarked fetching logic

feature: toggling and fetching bookmark
